apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: auronix
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: server
          image: auronix-server:kind-v1
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: auronix-server
  namespace: auronix
spec:
  type: ClusterIP
