apiVersion: v1
kind: ConfigMap
metadata:
  name: auronix-config
  namespace: auronix
  labels:
    app.kubernetes.io/name: auronix
data:
  PORT: "8080"
  DATABASE_URL: "jdbc:postgresql://postgres:5432/auronix"
  RABBITMQ_URL: "amqp://user:user@rabbitmq:5672/"
  REDIS_URL: "redis://redis:6379"
  JPA_DDL_AUTO: "update"
  JPA_SHOW_SQL: "true"
  JPA_FORMAT_SQL: "true"
