apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: auronix
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: server
          image: jpplay/auronix-server@sha256:0000000000000000000000000000000000000000000000000000000000000000
          imagePullPolicy: IfNotPresent
